import { useState, useCallback, useEffect } from 'react';
import { summarizeNote, getActiveProvider, type ActiveProviderResponse } from '../../services/aiService';

interface NoteSummarizerProps {
  noteId: string;
  content: string;
}

const NoteSummarizer: React.FC<NoteSummarizerProps> = ({ noteId, content }) => {
  const [summary, setSummary] = useState<string | null>(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [activeProvider, setActiveProvider] = useState<ActiveProviderResponse | null>(null);

  useEffect(() => {
    const loadProvider = async () => {
      try {
        const provider = await getActiveProvider();
        setActiveProvider(provider);
      } catch {
        // Silently fail - provider info is optional
      }
    };
    loadProvider();
  }, []);

  const handleSummarize = useCallback(async () => {
    if (!content.trim()) {
      setError('Note content is empty.');
      return;
    }

    setLoading(true);
    setError(null);
    setSummary(null);

    try {
      const result = await summarizeNote({ noteId, content });
      setSummary(result.summary);
    } catch (err: unknown) {
      const message = err instanceof Error ? err.message : 'Failed to summarize note.';
      setError(message);
    } finally {
      setLoading(false);
    }
  }, [noteId, content]);

  if (loading) {
    return (
      <div style={{
        padding: '16px',
        borderRadius: '8px',
        backgroundColor: '#f8f9fa',
        border: '1px solid #e9ecef',
        textAlign: 'center'
      }}>
        <div style={{
          display: 'inline-block',
          width: '32px',
          height: '32px',
          border: '3px solid #e9ecef',
          borderTopColor: '#007bff',
          borderRadius: '50%',
          animation: 'spin 0.8s linear infinite'
        }} />
        <p style={{ marginTop: '12px', color: '#6c757d' }}>Summarizing with AI...</p>
        <style>{`@keyframes spin { to { transform: rotate(360deg); } }`}</style>
      </div>
    );
  }

  if (error) {
    return (
      <div style={{
        padding: '12px 16px',
        borderRadius: '8px',
        backgroundColor: '#fff5f5',
        border: '1px solid #fed7d7',
        color: '#c53030',
        marginBottom: '12px'
      }}>
        <strong>Error:</strong> {error}
        <button
          onClick={() => setError(null)}
          style={{
            marginLeft: '12px',
            padding: '4px 12px',
            border: '1px solid #fc8181',
            borderRadius: '4px',
            backgroundColor: 'white',
            cursor: 'pointer',
            color: '#c53030'
          }}
        >
          Dismiss
        </button>
      </div>
    );
  }

  if (summary) {
    return (
      <div style={{
        padding: '16px',
        borderRadius: '8px',
        backgroundColor: '#f0f9ff',
        border: '1px solid #bae6fd',
        marginTop: '12px'
      }}>
        <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '8px' }}>
          <h4 style={{ margin: 0, color: '#0369a1' }}>📝 AI Summary</h4>
          {activeProvider && (
            <span style={{
              fontSize: '12px',
              color: '#64748b',
              backgroundColor: 'white',
              padding: '2px 8px',
              borderRadius: '12px',
              border: '1px solid #e2e8f0'
            }}>
              Generated by {activeProvider.activeProvider}
            </span>
          )}
        </div>
        <p style={{ whiteSpace: 'pre-wrap', margin: 0, lineHeight: '1.6', color: '#334155' }}>
          {summary}
        </p>
      </div>
    );
  }

  return (
    <div>
      <button
        onClick={handleSummarize}
        disabled={!content.trim()}
        style={{
          padding: '10px 20px',
          backgroundColor: content.trim() ? '#007bff' : '#94a3b8',
          color: 'white',
          border: 'none',
          borderRadius: '6px',
          cursor: content.trim() ? 'pointer' : 'not-allowed',
          fontSize: '14px',
          fontWeight: 500,
          display: 'flex',
          alignItems: 'center',
          gap: '8px'
        }}
      >
        ✨ Summarize with AI
      </button>
      {activeProvider && (
        <p style={{ fontSize: '12px', color: '#94a3b8', marginTop: '8px' }}>
          Powered by {activeProvider.activeProvider} ({activeProvider.model})
        </p>
      )}
    </div>
  );
};

export default NoteSummarizer;